MCP_DISTRACTOR_FUNCTIONS = [
    # HubSpot (12 tools)
    {"name": "create_contact", "description": "Create a new contact in HubSpot CRM", "parameters": {"type": "object", "properties": {"email": {"type": "string", "description": "Contact email address"}, "firstname": {"type": "string", "description": "Contact first name"}}, "required": ["email"]}},
    {"name": "update_company", "description": "Update company properties in HubSpot", "parameters": {"type": "object", "properties": {"company_id": {"type": "string", "description": "HubSpot company ID"}, "properties": {"type": "object", "description": "Company properties to update"}}, "required": ["company_id"]}},
    {"name": "get_deal", "description": "Get deal details by ID in HubSpot", "parameters": {"type": "object", "properties": {"deal_id": {"type": "string", "description": "HubSpot deal ID"}}, "required": ["deal_id"]}},
    {"name": "search_contacts", "description": "Search contacts by property values in HubSpot", "parameters": {"type": "object", "properties": {"query": {"type": "string", "description": "Search query string"}, "limit": {"type": "integer", "description": "Max results to return"}}, "required": ["query"]}},
    {"name": "create_task", "description": "Create a task in HubSpot CRM", "parameters": {"type": "object", "properties": {"subject": {"type": "string", "description": "Task subject"}, "due_date": {"type": "string", "description": "Task due date"}, "owner_id": {"type": "string", "description": "HubSpot owner ID"}}, "required": ["subject"]}},
    {"name": "list_pipelines", "description": "List all deal pipelines in HubSpot", "parameters": {"type": "object", "properties": {"include_properties": {"type": "boolean", "description": "Include pipeline stage properties"}}, "required": []}},
    {"name": "get_engagement", "description": "Get engagement details by ID in HubSpot", "parameters": {"type": "object", "properties": {"engagement_id": {"type": "string", "description": "Engagement record ID"}}, "required": ["engagement_id"]}},
    {"name": "create_note", "description": "Create a note on a record in HubSpot", "parameters": {"type": "object", "properties": {"body": {"type": "string", "description": "Note body text"}, "associations": {"type": "array", "description": "Associated record IDs"}}, "required": ["body"]}},
    {"name": "associate_record", "description": "Associate two CRM records in HubSpot", "parameters": {"type": "object", "properties": {"from_id": {"type": "string", "description": "Source record ID"}, "to_id": {"type": "string", "description": "Target record ID"}, "type": {"type": "string", "description": "Association type"}}, "required": ["from_id", "to_id"]}},
    {"name": "get_owner", "description": "Get HubSpot owner by ID", "parameters": {"type": "object", "properties": {"owner_id": {"type": "string", "description": "HubSpot owner ID"}}, "required": ["owner_id"]}},
    {"name": "list_companies", "description": "List companies with filtering in HubSpot", "parameters": {"type": "object", "properties": {"limit": {"type": "integer", "description": "Max companies to return"}, "after": {"type": "string", "description": "Pagination cursor"}}, "required": []}},
    {"name": "create_deal", "description": "Create a new deal in HubSpot CRM", "parameters": {"type": "object", "properties": {"dealname": {"type": "string", "description": "Deal name"}, "amount": {"type": "number", "description": "Deal amount"}, "pipeline": {"type": "string", "description": "Pipeline ID"}}, "required": ["dealname"]}},

    # Salesforce (12 tools)
    {"name": "query_sobject", "description": "Query SObject records using SOQL in Salesforce", "parameters": {"type": "object", "properties": {"query": {"type": "string", "description": "SOQL query string"}, "limit": {"type": "integer", "description": "Max records to return"}}, "required": ["query"]}},
    {"name": "create_sobject", "description": "Create a new SObject record in Salesforce", "parameters": {"type": "object", "properties": {"object_type": {"type": "string", "description": "SObject type name"}, "fields": {"type": "object", "description": "Field values to set"}}, "required": ["object_type", "fields"]}},
    {"name": "update_sobject", "description": "Update an existing SObject record in Salesforce", "parameters": {"type": "object", "properties": {"object_type": {"type": "string", "description": "SObject type name"}, "record_id": {"type": "string", "description": "Record ID to update"}, "fields": {"type": "object", "description": "Field values to update"}}, "required": ["object_type", "record_id", "fields"]}},
    {"name": "delete_sobject", "description": "Delete an SObject record from Salesforce", "parameters": {"type": "object", "properties": {"object_type": {"type": "string", "description": "SObject type name"}, "record_id": {"type": "string", "description": "Record ID to delete"}}, "required": ["object_type", "record_id"]}},
    {"name": "describe_object", "description": "Get metadata for an SObject in Salesforce", "parameters": {"type": "object", "properties": {"object_type": {"type": "string", "description": "SObject type to describe"}}, "required": ["object_type"]}},
    {"name": "search_records", "description": "Search records using SOSL in Salesforce", "parameters": {"type": "object", "properties": {"query": {"type": "string", "description": "SOSL search query"}, "object_types": {"type": "array", "description": "SObject types to search"}}, "required": ["query"]}},
    {"name": "run_apex", "description": "Execute anonymous Apex code in Salesforce", "parameters": {"type": "object", "properties": {"code": {"type": "string", "description": "Apex code to execute"}, "log_level": {"type": "string", "description": "Debug log level"}}, "required": ["code"]}},
    {"name": "get_user_info", "description": "Get current Salesforce user information", "parameters": {"type": "object", "properties": {"user_id": {"type": "string", "description": "User ID to retrieve"}}, "required": []}},
    {"name": "query_data_cloud", "description": "Query Data Cloud objects in Salesforce", "parameters": {"type": "object", "properties": {"query": {"type": "string", "description": "Data Cloud SQL query"}}, "required": ["query"]}},
    {"name": "create_report", "description": "Create a Salesforce report from a template", "parameters": {"type": "object", "properties": {"name": {"type": "string", "description": "Report name"}, "folder_id": {"type": "string", "description": "Folder to save in"}, "report_type": {"type": "string", "description": "Report type metadata"}}, "required": ["name", "report_type"]}},
    {"name": "run_report", "description": "Run an existing Salesforce report by ID", "parameters": {"type": "object", "properties": {"report_id": {"type": "string", "description": "Report ID to run"}}, "required": ["report_id"]}},
    {"name": "list_dashboards", "description": "List Salesforce dashboards the user can access", "parameters": {"type": "object", "properties": {"folder_id": {"type": "string", "description": "Optional folder filter"}}, "required": []}},

    # Notion (10 tools)
    {"name": "search_pages", "description": "Search Notion pages by title text", "parameters": {"type": "object", "properties": {"query": {"type": "string", "description": "Search query text"}, "sort": {"type": "object", "description": "Sort direction for results"}}, "required": ["query"]}},
    {"name": "get_page", "description": "Get a Notion page by page ID", "parameters": {"type": "object", "properties": {"page_id": {"type": "string", "description": "Notion page UUID"}}, "required": ["page_id"]}},
    {"name": "create_page", "description": "Create a new page in a Notion database", "parameters": {"type": "object", "properties": {"parent_id": {"type": "string", "description": "Parent page or database ID"}, "properties": {"type": "object", "description": "Page property values"}}, "required": ["parent_id", "properties"]}},
    {"name": "update_page", "description": "Update properties of a Notion page", "parameters": {"type": "object", "properties": {"page_id": {"type": "string", "description": "Page ID to update"}, "properties": {"type": "object", "description": "Properties to modify"}}, "required": ["page_id", "properties"]}},
    {"name": "append_block", "description": "Append child blocks to a Notion block", "parameters": {"type": "object", "properties": {"block_id": {"type": "string", "description": "Parent block ID"}, "children": {"type": "array", "description": "Block objects to append"}}, "required": ["block_id", "children"]}},
    {"name": "list_databases", "description": "List all Notion databases accessible to integration", "parameters": {"type": "object", "properties": {"page_size": {"type": "integer", "description": "Number of databases per page"}}, "required": []}},
    {"name": "query_database", "description": "Query a Notion database with filters", "parameters": {"type": "object", "properties": {"database_id": {"type": "string", "description": "Database ID to query"}, "filter": {"type": "object", "description": "Database filter conditions"}}, "required": ["database_id"]}},
    {"name": "create_database_item", "description": "Create an item in a Notion database", "parameters": {"type": "object", "properties": {"database_id": {"type": "string", "description": "Target database ID"}, "properties": {"type": "object", "description": "Item property values"}}, "required": ["database_id", "properties"]}},
    {"name": "archive_page", "description": "Archive or unarchive a Notion page", "parameters": {"type": "object", "properties": {"page_id": {"type": "string", "description": "Page ID to archive"}, "archived": {"type": "boolean", "description": "True to archive"}}, "required": ["page_id", "archived"]}},
    {"name": "list_users", "description": "List all users in a Notion workspace", "parameters": {"type": "object", "properties": {"page_size": {"type": "integer", "description": "Max users per page"}}, "required": []}},

    # Jira/Confluence (14 tools)
    {"name": "search_issues", "description": "Search Jira issues using JQL queries", "parameters": {"type": "object", "properties": {"jql": {"type": "string", "description": "JQL query string"}, "max_results": {"type": "integer", "description": "Max results to return"}}, "required": ["jql"]}},
    {"name": "get_issue", "description": "Get a Jira issue by issue key or ID", "parameters": {"type": "object", "properties": {"issue_key": {"type": "string", "description": "Jira issue key"}}, "required": ["issue_key"]}},
    {"name": "create_issue", "description": "Create a new issue in a Jira project", "parameters": {"type": "object", "properties": {"project_key": {"type": "string", "description": "Project key"}, "summary": {"type": "string", "description": "Issue summary"}, "issuetype": {"type": "string", "description": "Issue type name"}}, "required": ["project_key", "summary", "issuetype"]}},
    {"name": "update_issue", "description": "Update fields on a Jira issue", "parameters": {"type": "object", "properties": {"issue_key": {"type": "string", "description": "Issue key to update"}, "fields": {"type": "object", "description": "Fields to update"}}, "required": ["issue_key", "fields"]}},
    {"name": "transition_issue", "description": "Transition a Jira issue through a workflow", "parameters": {"type": "object", "properties": {"issue_key": {"type": "string", "description": "Issue key"}, "transition_id": {"type": "string", "description": "Transition ID"}, "fields": {"type": "object", "description": "Transition field updates"}}, "required": ["issue_key", "transition_id"]}},
    {"name": "add_comment", "description": "Add a comment to a Jira issue", "parameters": {"type": "object", "properties": {"issue_key": {"type": "string", "description": "Issue key"}, "body": {"type": "string", "description": "Comment body text"}}, "required": ["issue_key", "body"]}},
    {"name": "list_projects", "description": "List all projects in Jira", "parameters": {"type": "object", "properties": {"include_archived": {"type": "boolean", "description": "Include archived projects"}}, "required": []}},
    {"name": "search_confluence", "description": "Search Confluence pages by title and content", "parameters": {"type": "object", "properties": {"query": {"type": "string", "description": "Search query string"}, "limit": {"type": "integer", "description": "Max results"}}, "required": ["query"]}},
    {"name": "get_page_content", "description": "Get Confluence page content by page ID", "parameters": {"type": "object", "properties": {"page_id": {"type": "string", "description": "Confluence page ID"}}, "required": ["page_id"]}},
    {"name": "create_confluence_page", "description": "Create a new Confluence page in a space", "parameters": {"type": "object", "properties": {"space_key": {"type": "string", "description": "Confluence space key"}, "title": {"type": "string", "description": "Page title"}, "body": {"type": "string", "description": "Page body in storage format"}}, "required": ["space_key", "title", "body"]}},
    {"name": "list_sprints", "description": "List all sprints in a Jira board", "parameters": {"type": "object", "properties": {"board_id": {"type": "integer", "description": "Board ID"}, "state": {"type": "string", "description": "Sprint state filter"}}, "required": ["board_id"]}},
    {"name": "get_board", "description": "Get Jira board details by board ID", "parameters": {"type": "object", "properties": {"board_id": {"type": "integer", "description": "Board ID"}}, "required": ["board_id"]}},
    {"name": "search_users", "description": "Search users across Jira and Confluence", "parameters": {"type": "object", "properties": {"query": {"type": "string", "description": "Username or display name query"}, "max_results": {"type": "integer", "description": "Max results"}}, "required": ["query"]}},
    {"name": "get_attachments", "description": "List attachments on a Confluence page", "parameters": {"type": "object", "properties": {"page_id": {"type": "string", "description": "Confluence page ID"}}, "required": ["page_id"]}},

    # Slack (12 tools)
    {"name": "send_message", "description": "Send a message to a Slack channel", "parameters": {"type": "object", "properties": {"channel": {"type": "string", "description": "Channel ID or name"}, "text": {"type": "string", "description": "Message text"}}, "required": ["channel", "text"]}},
    {"name": "search_messages", "description": "Search messages across Slack workspace", "parameters": {"type": "object", "properties": {"query": {"type": "string", "description": "Search query"}, "sort": {"type": "string", "description": "Sort by score or timestamp"}}, "required": ["query"]}},
    {"name": "list_channels", "description": "List public channels in Slack workspace", "parameters": {"type": "object", "properties": {"limit": {"type": "integer", "description": "Max channels to return"}, "cursor": {"type": "string", "description": "Pagination cursor"}}, "required": []}},
    {"name": "get_channel_history", "description": "Get message history for a Slack channel", "parameters": {"type": "object", "properties": {"channel": {"type": "string", "description": "Channel ID"}, "limit": {"type": "integer", "description": "Max messages"}}, "required": ["channel"]}},
    {"name": "add_reaction", "description": "Add an emoji reaction to a Slack message", "parameters": {"type": "object", "properties": {"channel": {"type": "string", "description": "Channel ID"}, "timestamp": {"type": "string", "description": "Message timestamp"}, "reaction": {"type": "string", "description": "Emoji reaction name"}}, "required": ["channel", "timestamp", "reaction"]}},
    {"name": "upload_file", "description": "Upload a file to a Slack channel", "parameters": {"type": "object", "properties": {"channel": {"type": "string", "description": "Channel ID"}, "file": {"type": "string", "description": "File content as base64"}, "filename": {"type": "string", "description": "Filename with extension"}}, "required": ["channel", "file", "filename"]}},
    {"name": "get_user_info", "description": "Get Slack user profile by user ID", "parameters": {"type": "object", "properties": {"user_id": {"type": "string", "description": "Slack user ID"}}, "required": ["user_id"]}},
    {"name": "create_channel", "description": "Create a new Slack channel", "parameters": {"type": "object", "properties": {"name": {"type": "string", "description": "Channel name"}, "is_private": {"type": "boolean", "description": "Private channel flag"}}, "required": ["name"]}},
    {"name": "invite_user", "description": "Invite a user to a Slack channel", "parameters": {"type": "object", "properties": {"channel": {"type": "string", "description": "Channel ID"}, "user_id": {"type": "string", "description": "User ID to invite"}}, "required": ["channel", "user_id"]}},
    {"name": "search_files", "description": "Search for files in Slack workspace", "parameters": {"type": "object", "properties": {"query": {"type": "string", "description": "Search query"}, "count": {"type": "integer", "description": "Max file results"}}, "required": ["query"]}},
    {"name": "get_thread", "description": "Get all replies in a Slack thread", "parameters": {"type": "object", "properties": {"channel": {"type": "string", "description": "Channel ID"}, "thread_ts": {"type": "string", "description": "Parent message timestamp"}}, "required": ["channel", "thread_ts"]}},
    {"name": "set_topic", "description": "Set the topic for a Slack channel", "parameters": {"type": "object", "properties": {"channel": {"type": "string", "description": "Channel ID"}, "topic": {"type": "string", "description": "New channel topic"}}, "required": ["channel", "topic"]}},

    # Google Workspace (15 tools)
    {"name": "get_drive_file", "description": "Get metadata of a Google Drive file", "parameters": {"type": "object", "properties": {"file_id": {"type": "string", "description": "Google Drive file ID"}}, "required": ["file_id"]}},
    {"name": "list_drive_folder", "description": "List files and folders in a Drive folder", "parameters": {"type": "object", "properties": {"folder_id": {"type": "string", "description": "Folder ID to list"}, "page_size": {"type": "integer", "description": "Max results"}}, "required": ["folder_id"]}},
    {"name": "search_gmail", "description": "Search Gmail messages by query", "parameters": {"type": "object", "properties": {"query": {"type": "string", "description": "Gmail search query"}, "max_results": {"type": "integer", "description": "Max results"}}, "required": ["query"]}},
    {"name": "send_email", "description": "Send an email via Gmail SMTP", "parameters": {"type": "object", "properties": {"to": {"type": "string", "description": "Recipient email"}, "subject": {"type": "string", "description": "Email subject"}, "body": {"type": "string", "description": "Email body text"}}, "required": ["to", "subject", "body"]}},
    {"name": "create_calendar_event", "description": "Create a Google Calendar event", "parameters": {"type": "object", "properties": {"summary": {"type": "string", "description": "Event title"}, "start_time": {"type": "string", "description": "Start datetime"}, "end_time": {"type": "string", "description": "End datetime"}}, "required": ["summary", "start_time", "end_time"]}},
    {"name": "list_events", "description": "List upcoming Google Calendar events", "parameters": {"type": "object", "properties": {"calendar_id": {"type": "string", "description": "Calendar ID"}, "time_min": {"type": "string", "description": "Start of time range"}}, "required": []}},
    {"name": "search_contacts", "description": "Search Google Contacts by query", "parameters": {"type": "object", "properties": {"query": {"type": "string", "description": "Contact search query"}, "page_size": {"type": "integer", "description": "Max results"}}, "required": ["query"]}},
    {"name": "get_document", "description": "Get content of a Google Docs document", "parameters": {"type": "object", "properties": {"document_id": {"type": "string", "description": "Google Docs document ID"}}, "required": ["document_id"]}},
    {"name": "create_sheet", "description": "Create a new Google Sheets spreadsheet", "parameters": {"type": "object", "properties": {"title": {"type": "string", "description": "Spreadsheet title"}, "sheets": {"type": "array", "description": "Initial sheet names"}}, "required": ["title"]}},
    {"name": "update_spreadsheet", "description": "Update cell values in Google Sheets", "parameters": {"type": "object", "properties": {"spreadsheet_id": {"type": "string", "description": "Spreadsheet ID"}, "range": {"type": "string", "description": "A1 notation range"}, "values": {"type": "array", "description": "Row values to write"}}, "required": ["spreadsheet_id", "range", "values"]}},
    {"name": "list_slides", "description": "List slides in a Google Slides presentation", "parameters": {"type": "object", "properties": {"presentation_id": {"type": "string", "description": "Slides presentation ID"}}, "required": ["presentation_id"]}},
    {"name": "get_analytics_data", "description": "Get Google Analytics report data", "parameters": {"type": "object", "properties": {"property_id": {"type": "string", "description": "GA4 property ID"}, "date_range": {"type": "object", "description": "Start and end dates"}, "metrics": {"type": "array", "description": "Metric names"}}, "required": ["property_id", "metrics"]}},
    {"name": "create_folder", "description": "Create a folder in Google Drive", "parameters": {"type": "object", "properties": {"name": {"type": "string", "description": "Folder name"}, "parent_id": {"type": "string", "description": "Parent folder ID"}}, "required": ["name"]}},
    {"name": "search_calendar", "description": "Search Google Calendar events by text", "parameters": {"type": "object", "properties": {"query": {"type": "string", "description": "Event search text"}, "calendar_id": {"type": "string", "description": "Calendar to search"}}, "required": ["query"]}},
    {"name": "share_drive_file", "description": "Share a Drive file with a user or group", "parameters": {"type": "object", "properties": {"file_id": {"type": "string", "description": "File ID to share"}, "email": {"type": "string", "description": "Recipient email"}, "role": {"type": "string", "description": "Permission role"}}, "required": ["file_id", "email", "role"]}},

    # Attio (16 tools)
    {"name": "search_records", "description": "Search Attio records across all objects", "parameters": {"type": "object", "properties": {"query": {"type": "string", "description": "Search query"}, "object_id": {"type": "string", "description": "Optional object type filter"}}, "required": ["query"]}},
    {"name": "get_record", "description": "Get a single Attio record by ID", "parameters": {"type": "object", "properties": {"record_id": {"type": "string", "description": "Attio record ID"}, "object_id": {"type": "string", "description": "Object type ID"}}, "required": ["record_id", "object_id"]}},
    {"name": "create_record", "description": "Create a new record in an Attio object", "parameters": {"type": "object", "properties": {"object_id": {"type": "string", "description": "Object type ID"}, "attributes": {"type": "object", "description": "Attribute values"}}, "required": ["object_id", "attributes"]}},
    {"name": "update_record", "description": "Update attribute values on an Attio record", "parameters": {"type": "object", "properties": {"record_id": {"type": "string", "description": "Record ID"}, "object_id": {"type": "string", "description": "Object type ID"}, "attributes": {"type": "object", "description": "Updated attribute values"}}, "required": ["record_id", "object_id", "attributes"]}},
    {"name": "list_objects", "description": "List all object types in Attio workspace", "parameters": {"type": "object", "properties": {"include_standard": {"type": "boolean", "description": "Include standard objects"}}, "required": []}},
    {"name": "get_object", "description": "Get an Attio object type definition", "parameters": {"type": "object", "properties": {"object_id": {"type": "string", "description": "Object type ID"}}, "required": ["object_id"]}},
    {"name": "add_note_to_record", "description": "Add a note to a record in Attio", "parameters": {"type": "object", "properties": {"record_id": {"type": "string", "description": "Record ID"}, "object_id": {"type": "string", "description": "Object type ID"}, "content": {"type": "string", "description": "Note content"}}, "required": ["record_id", "object_id", "content"]}},
    {"name": "list_comments", "description": "List comments on an Attio record", "parameters": {"type": "object", "properties": {"record_id": {"type": "string", "description": "Record ID"}, "object_id": {"type": "string", "description": "Object type ID"}}, "required": ["record_id", "object_id"]}},
    {"name": "add_comment", "description": "Add a comment to an Attio record", "parameters": {"type": "object", "properties": {"record_id": {"type": "string", "description": "Record ID"}, "object_id": {"type": "string", "description": "Object type ID"}, "content": {"type": "string", "description": "Comment content"}}, "required": ["record_id", "object_id", "content"]}},
    {"name": "create_task", "description": "Create a task in Attio CRM", "parameters": {"type": "object", "properties": {"title": {"type": "string", "description": "Task title"}, "assignee_id": {"type": "string", "description": "Assignee user ID"}, "due_date": {"type": "string", "description": "Due date"}}, "required": ["title"]}},
    {"name": "list_tasks", "description": "List tasks in Attio with filters", "parameters": {"type": "object", "properties": {"status": {"type": "string", "description": "Filter by status"}, "assignee_id": {"type": "string", "description": "Filter by assignee"}}, "required": []}},
    {"name": "list_lists", "description": "List all lists in Attio workspace", "parameters": {"type": "object", "properties": {"object_id": {"type": "string", "description": "Filter by object type"}}, "required": []}},
    {"name": "add_to_list", "description": "Add a record to an Attio list", "parameters": {"type": "object", "properties": {"list_id": {"type": "string", "description": "List ID"}, "record_id": {"type": "string", "description": "Record to add"}}, "required": ["list_id", "record_id"]}},
    {"name": "create_meeting", "description": "Create a meeting entry in Attio", "parameters": {"type": "object", "properties": {"title": {"type": "string", "description": "Meeting title"}, "start_time": {"type": "string", "description": "Meeting start time"}, "participants": {"type": "array", "description": "Participant record IDs"}}, "required": ["title", "start_time"]}},
    {"name": "link_records", "description": "Link two records in Attio CRM", "parameters": {"type": "object", "properties": {"record_id": {"type": "string", "description": "Source record ID"}, "linked_record_id": {"type": "string", "description": "Target record ID"}, "link_type": {"type": "string", "description": "Link type identifier"}}, "required": ["record_id", "linked_record_id", "link_type"]}},
    {"name": "search_entries", "description": "Search entries in an Attio list", "parameters": {"type": "object", "properties": {"list_id": {"type": "string", "description": "List ID to search"}, "query": {"type": "string", "description": "Search text"}}, "required": ["list_id", "query"]}},

    # Twilio (6 tools)
    {"name": "send_sms", "description": "Send an SMS message via Twilio", "parameters": {"type": "object", "properties": {"to": {"type": "string", "description": "Recipient phone number"}, "from": {"type": "string", "description": "Twilio phone number"}, "body": {"type": "string", "description": "Message body"}}, "required": ["to", "from", "body"]}},
    {"name": "search_twilio", "description": "Search Twilio knowledge base articles", "parameters": {"type": "object", "properties": {"query": {"type": "string", "description": "Search query"}, "page_size": {"type": "integer", "description": "Results per page"}}, "required": ["query"]}},
    {"name": "list_messages", "description": "List recent messages in a Twilio account", "parameters": {"type": "object", "properties": {"limit": {"type": "integer", "description": "Max messages"}, "to": {"type": "string", "description": "Filter by recipient"}}, "required": []}},
    {"name": "get_message", "description": "Get a Twilio message by SID", "parameters": {"type": "object", "properties": {"message_sid": {"type": "string", "description": "Message SID"}}, "required": ["message_sid"]}},
    {"name": "retrieve_call_logs", "description": "Retrieve Twilio call log records", "parameters": {"type": "object", "properties": {"limit": {"type": "integer", "description": "Max call logs"}, "start_time": {"type": "string", "description": "Filter from date"}}, "required": []}},
    {"name": "search_knowledge_base", "description": "Search Twilio Help Center articles", "parameters": {"type": "object", "properties": {"query": {"type": "string", "description": "Search keywords"}, "category": {"type": "string", "description": "Article category"}}, "required": ["query"]}},

    # Asana (10 tools)
    {"name": "create_task", "description": "Create a task in Asana project", "parameters": {"type": "object", "properties": {"project_id": {"type": "string", "description": "Project ID"}, "name": {"type": "string", "description": "Task name"}, "assignee": {"type": "string", "description": "Assignee user ID"}}, "required": ["project_id", "name"]}},
    {"name": "get_task", "description": "Get an Asana task by task ID", "parameters": {"type": "object", "properties": {"task_id": {"type": "string", "description": "Asana task ID"}, "opt_fields": {"type": "array", "description": "Fields to include"}}, "required": ["task_id"]}},
    {"name": "update_task", "description": "Update an existing Asana task", "parameters": {"type": "object", "properties": {"task_id": {"type": "string", "description": "Task ID"}, "fields": {"type": "object", "description": "Fields to update"}}, "required": ["task_id", "fields"]}},
    {"name": "search_tasks", "description": "Search tasks in Asana by text", "parameters": {"type": "object", "properties": {"query": {"type": "string", "description": "Search query"}, "project_id": {"type": "string", "description": "Filter by project"}}, "required": ["query"]}},
    {"name": "list_projects", "description": "List all projects in Asana workspace", "parameters": {"type": "object", "properties": {"workspace_id": {"type": "string", "description": "Workspace ID"}, "archived": {"type": "boolean", "description": "Include archived"}}, "required": []}},
    {"name": "create_project", "description": "Create a new Asana project", "parameters": {"type": "object", "properties": {"name": {"type": "string", "description": "Project name"}, "workspace_id": {"type": "string", "description": "Workspace ID"}, "team_id": {"type": "string", "description": "Team ID"}}, "required": ["name", "workspace_id"]}},
    {"name": "add_comment", "description": "Add a comment to an Asana task", "parameters": {"type": "object", "properties": {"task_id": {"type": "string", "description": "Task ID"}, "text": {"type": "string", "description": "Comment text"}}, "required": ["task_id", "text"]}},
    {"name": "list_sections", "description": "List sections in an Asana project", "parameters": {"type": "object", "properties": {"project_id": {"type": "string", "description": "Project ID"}}, "required": ["project_id"]}},
    {"name": "get_team", "description": "Get team details in Asana", "parameters": {"type": "object", "properties": {"team_id": {"type": "string", "description": "Team ID"}}, "required": ["team_id"]}},
    {"name": "update_project", "description": "Update project properties in Asana", "parameters": {"type": "object", "properties": {"project_id": {"type": "string", "description": "Project ID"}, "fields": {"type": "object", "description": "Project field updates"}}, "required": ["project_id", "fields"]}},

    # QuickBooks (8 tools)
    {"name": "create_invoice", "description": "Create an invoice in QuickBooks", "parameters": {"type": "object", "properties": {"customer_id": {"type": "string", "description": "Customer ID"}, "lines": {"type": "array", "description": "Invoice line items"}, "due_date": {"type": "string", "description": "Payment due date"}}, "required": ["customer_id", "lines"]}},
    {"name": "get_customer", "description": "Get customer details in QuickBooks", "parameters": {"type": "object", "properties": {"customer_id": {"type": "string", "description": "QuickBooks customer ID"}}, "required": ["customer_id"]}},
    {"name": "list_invoices", "description": "List invoices with filtering in QuickBooks", "parameters": {"type": "object", "properties": {"status": {"type": "string", "description": "Invoice status filter"}, "start_date": {"type": "string", "description": "Invoice start date"}}, "required": []}},
    {"name": "create_estimate", "description": "Create an estimate in QuickBooks", "parameters": {"type": "object", "properties": {"customer_id": {"type": "string", "description": "Customer ID"}, "lines": {"type": "array", "description": "Estimate line items"}}, "required": ["customer_id", "lines"]}},
    {"name": "search_products", "description": "Search products and services in QuickBooks", "parameters": {"type": "object", "properties": {"query": {"type": "string", "description": "Search query"}, "active_only": {"type": "boolean", "description": "Only active items"}}, "required": ["query"]}},
    {"name": "create_payment", "description": "Record a payment in QuickBooks", "parameters": {"type": "object", "properties": {"customer_id": {"type": "string", "description": "Customer ID"}, "amount": {"type": "number", "description": "Payment amount"}, "invoice_ids": {"type": "array", "description": "Invoices to apply payment"}}, "required": ["customer_id", "amount"]}},
    {"name": "list_accounts", "description": "List chart of accounts in QuickBooks", "parameters": {"type": "object", "properties": {"account_type": {"type": "string", "description": "Filter by account type"}}, "required": []}},
    {"name": "get_company_info", "description": "Get QuickBooks company information", "parameters": {"type": "object", "properties": {"company_id": {"type": "string", "description": "Company ID"}}, "required": []}},

    # Adobe (7 tools)
    {"name": "create_image", "description": "Generate an image using Adobe Firefly", "parameters": {"type": "object", "properties": {"prompt": {"type": "string", "description": "Text prompt for image"}, "size": {"type": "string", "description": "Output image size"}, "count": {"type": "integer", "description": "Number of images"}}, "required": ["prompt"]}},
    {"name": "edit_image", "description": "Edit an image using Adobe Photoshop API", "parameters": {"type": "object", "properties": {"asset_id": {"type": "string", "description": "Adobe asset ID"}, "edits": {"type": "object", "description": "Edit operations"}}, "required": ["asset_id", "edits"]}},
    {"name": "generate_template", "description": "Generate a design template in Adobe Express", "parameters": {"type": "object", "properties": {"template_type": {"type": "string", "description": "Template category"}, "theme": {"type": "string", "description": "Design theme"}, "brand_id": {"type": "string", "description": "Brand kit ID"}}, "required": ["template_type"]}},
    {"name": "add_text_to_image", "description": "Add text overlay to an Adobe image", "parameters": {"type": "object", "properties": {"asset_id": {"type": "string", "description": "Image asset ID"}, "text": {"type": "string", "description": "Text to overlay"}, "position": {"type": "string", "description": "Text position"}}, "required": ["asset_id", "text"]}},
    {"name": "resize_image", "description": "Resize an image with Adobe Photoshop", "parameters": {"type": "object", "properties": {"asset_id": {"type": "string", "description": "Image asset ID"}, "width": {"type": "integer", "description": "Target width"}, "height": {"type": "integer", "description": "Target height"}}, "required": ["asset_id", "width", "height"]}},
    {"name": "get_asset_info", "description": "Get metadata for an Adobe asset", "parameters": {"type": "object", "properties": {"asset_id": {"type": "string", "description": "Adobe asset ID"}}, "required": ["asset_id"]}},
    {"name": "search_assets", "description": "Search Adobe Experience Cloud assets", "parameters": {"type": "object", "properties": {"query": {"type": "string", "description": "Search keywords"}, "limit": {"type": "integer", "description": "Max results"}}, "required": ["query"]}},

    # Microsoft M365 (15 tools)
    {"name": "send_outlook_mail", "description": "Send an email via Microsoft Outlook", "parameters": {"type": "object", "properties": {"to": {"type": "array", "description": "Recipient emails"}, "subject": {"type": "string", "description": "Email subject"}, "body": {"type": "string", "description": "Email body content"}}, "required": ["to", "subject", "body"]}},
    {"name": "list_calendar_events", "description": "List events from Outlook calendar", "parameters": {"type": "object", "properties": {"calendar_id": {"type": "string", "description": "Calendar ID"}, "start_date": {"type": "string", "description": "Range start"}}, "required": []}},
    {"name": "create_teams_message", "description": "Send a message to Microsoft Teams channel", "parameters": {"type": "object", "properties": {"team_id": {"type": "string", "description": "Team ID"}, "channel_id": {"type": "string", "description": "Channel ID"}, "message": {"type": "string", "description": "Message content"}}, "required": ["team_id", "channel_id", "message"]}},
    {"name": "search_sharepoint", "description": "Search files in SharePoint Online", "parameters": {"type": "object", "properties": {"query": {"type": "string", "description": "Search query"}, "site_id": {"type": "string", "description": "Site collection filter"}}, "required": ["query"]}},
    {"name": "get_onedrive_file", "description": "Get file metadata from OneDrive", "parameters": {"type": "object", "properties": {"file_id": {"type": "string", "description": "OneDrive file ID"}}, "required": ["file_id"]}},
    {"name": "create_word_doc", "description": "Create a Word document via Microsoft Graph", "parameters": {"type": "object", "properties": {"name": {"type": "string", "description": "Document filename"}, "content": {"type": "string", "description": "Document content in HTML"}, "drive_id": {"type": "string", "description": "OneDrive drive ID"}}, "required": ["name", "content"]}},
    {"name": "update_excel_cell", "description": "Update a cell value in Excel Online", "parameters": {"type": "object", "properties": {"workbook_id": {"type": "string", "description": "Excel workbook ID"}, "sheet_name": {"type": "string", "description": "Sheet name"}, "cell": {"type": "string", "description": "Cell reference"}, "value": {"type": "object", "description": "Cell value"}}, "required": ["workbook_id", "sheet_name", "cell", "value"]}},
    {"name": "list_planner_tasks", "description": "List tasks in Microsoft Planner plan", "parameters": {"type": "object", "properties": {"plan_id": {"type": "string", "description": "Planner plan ID"}, "filter": {"type": "string", "description": "OData filter"}}, "required": ["plan_id"]}},
    {"name": "get_team_info", "description": "Get Microsoft Team details by ID", "parameters": {"type": "object", "properties": {"team_id": {"type": "string", "description": "Team ID"}}, "required": ["team_id"]}},
    {"name": "list_channels", "description": "List channels in a Microsoft Team", "parameters": {"type": "object", "properties": {"team_id": {"type": "string", "description": "Team ID"}}, "required": ["team_id"]}},
    {"name": "share_file", "description": "Share a OneDrive file with another user", "parameters": {"type": "object", "properties": {"file_id": {"type": "string", "description": "File ID"}, "recipient_email": {"type": "string", "description": "Recipient email"}, "permission": {"type": "string", "description": "Read or write"}}, "required": ["file_id", "recipient_email", "permission"]}},
    {"name": "create_meeting", "description": "Create a Teams meeting via Graph API", "parameters": {"type": "object", "properties": {"subject": {"type": "string", "description": "Meeting subject"}, "start_time": {"type": "string", "description": "Start datetime"}, "end_time": {"type": "string", "description": "End datetime"}, "attendees": {"type": "array", "description": "Attendee emails"}}, "required": ["subject", "start_time", "end_time"]}},
    {"name": "list_contacts", "description": "List contacts from Outlook contact folder", "parameters": {"type": "object", "properties": {"folder_id": {"type": "string", "description": "Contact folder ID"}, "search": {"type": "string", "description": "Search term"}}, "required": []}},
    {"name": "search_outlook", "description": "Search Outlook mailbox for messages", "parameters": {"type": "object", "properties": {"query": {"type": "string", "description": "Search query"}, "folder_id": {"type": "string", "description": "Folder to search"}}, "required": ["query"]}},
    {"name": "get_excel_workbook", "description": "Get metadata of an Excel workbook", "parameters": {"type": "object", "properties": {"workbook_id": {"type": "string", "description": "Excel workbook ID"}}, "required": ["workbook_id"]}},

    # Oracle Cloud (7 tools)
    {"name": "list_compute_instances", "description": "List compute instances in OCI compartment", "parameters": {"type": "object", "properties": {"compartment_id": {"type": "string", "description": "OCI compartment ID"}, "limit": {"type": "integer", "description": "Max results"}}, "required": ["compartment_id"]}},
    {"name": "create_database", "description": "Create an Oracle Autonomous Database", "parameters": {"type": "object", "properties": {"compartment_id": {"type": "string", "description": "Compartment ID"}, "db_name": {"type": "string", "description": "Database name"}, "cpu_count": {"type": "integer", "description": "OCPU count"}}, "required": ["compartment_id", "db_name"]}},
    {"name": "query_autonomous_db", "description": "Run SQL query on Autonomous Database", "parameters": {"type": "object", "properties": {"database_id": {"type": "string", "description": "Autonomous DB ID"}, "query": {"type": "string", "description": "SQL query text"}}, "required": ["database_id", "query"]}},
    {"name": "list_buckets", "description": "List object storage buckets in OCI", "parameters": {"type": "object", "properties": {"namespace": {"type": "string", "description": "Object storage namespace"}, "compartment_id": {"type": "string", "description": "Compartment ID"}}, "required": ["namespace", "compartment_id"]}},
    {"name": "get_cost_report", "description": "Get cost and usage report for OCI", "parameters": {"type": "object", "properties": {"time_period": {"type": "string", "description": "Report time period"}, "granularity": {"type": "string", "description": "Daily or monthly"}}, "required": ["time_period"]}},
    {"name": "list_network_endpoints", "description": "List network endpoints in OCI VCN", "parameters": {"type": "object", "properties": {"compartment_id": {"type": "string", "description": "Compartment ID"}, "vcn_id": {"type": "string", "description": "VCN ID"}}, "required": ["compartment_id", "vcn_id"]}},
    {"name": "create_bucket", "description": "Create a new object storage bucket", "parameters": {"type": "object", "properties": {"namespace": {"type": "string", "description": "Object storage namespace"}, "name": {"type": "string", "description": "Bucket name"}, "compartment_id": {"type": "string", "description": "Compartment ID"}}, "required": ["namespace", "name", "compartment_id"]}},

    # Atera (6 tools)
    {"name": "list_devices", "description": "List all monitored devices in Atera", "parameters": {"type": "object", "properties": {"device_type": {"type": "string", "description": "Filter by device type"}, "page": {"type": "integer", "description": "Page number"}}, "required": []}},
    {"name": "get_device_info", "description": "Get detailed info for an Atera device", "parameters": {"type": "object", "properties": {"device_id": {"type": "string", "description": "Atera device ID"}}, "required": ["device_id"]}},
    {"name": "create_ticket", "description": "Create a new ticket in Atera", "parameters": {"type": "object", "properties": {"subject": {"type": "string", "description": "Ticket subject"}, "description": {"type": "string", "description": "Ticket description"}, "priority": {"type": "string", "description": "Priority level"}, "device_id": {"type": "string", "description": "Related device ID"}}, "required": ["subject", "description"]}},
    {"name": "list_tickets", "description": "List tickets in Atera with filters", "parameters": {"type": "object", "properties": {"status": {"type": "string", "description": "Ticket status filter"}, "page_size": {"type": "integer", "description": "Results per page"}}, "required": []}},
    {"name": "run_script", "description": "Run a script on an Atera device", "parameters": {"type": "object", "properties": {"device_id": {"type": "string", "description": "Target device ID"}, "script_id": {"type": "string", "description": "Script ID to execute"}}, "required": ["device_id", "script_id"]}},
    {"name": "get_alert", "description": "Get an Atera alert by alert ID", "parameters": {"type": "object", "properties": {"alert_id": {"type": "string", "description": "Alert ID"}}, "required": ["alert_id"]}},

    # GitHub (12 tools)
    {"name": "search_repos", "description": "Search GitHub repositories by query", "parameters": {"type": "object", "properties": {"query": {"type": "string", "description": "Search keywords"}, "sort": {"type": "string", "description": "Sort by stars or updated"}, "per_page": {"type": "integer", "description": "Results per page"}}, "required": ["query"]}},
    {"name": "get_repo", "description": "Get repository details from GitHub", "parameters": {"type": "object", "properties": {"owner": {"type": "string", "description": "Repository owner"}, "repo": {"type": "string", "description": "Repository name"}}, "required": ["owner", "repo"]}},
    {"name": "list_issues", "description": "List issues in a GitHub repository", "parameters": {"type": "object", "properties": {"owner": {"type": "string", "description": "Repository owner"}, "repo": {"type": "string", "description": "Repository name"}, "state": {"type": "string", "description": "Issue state filter"}}, "required": ["owner", "repo"]}},
    {"name": "create_issue", "description": "Create an issue in a GitHub repository", "parameters": {"type": "object", "properties": {"owner": {"type": "string", "description": "Repository owner"}, "repo": {"type": "string", "description": "Repository name"}, "title": {"type": "string", "description": "Issue title"}, "body": {"type": "string", "description": "Issue body"}}, "required": ["owner", "repo", "title"]}},
    {"name": "list_pull_requests", "description": "List pull requests in a GitHub repo", "parameters": {"type": "object", "properties": {"owner": {"type": "string", "description": "Repository owner"}, "repo": {"type": "string", "description": "Repository name"}, "state": {"type": "string", "description": "PR state filter"}}, "required": ["owner", "repo"]}},
    {"name": "get_pr", "description": "Get pull request details from GitHub", "parameters": {"type": "object", "properties": {"owner": {"type": "string", "description": "Repository owner"}, "repo": {"type": "string", "description": "Repository name"}, "pull_number": {"type": "integer", "description": "PR number"}}, "required": ["owner", "repo", "pull_number"]}},
    {"name": "list_workflows", "description": "List GitHub Actions workflows in a repo", "parameters": {"type": "object", "properties": {"owner": {"type": "string", "description": "Repository owner"}, "repo": {"type": "string", "description": "Repository name"}}, "required": ["owner", "repo"]}},
    {"name": "trigger_workflow", "description": "Trigger a GitHub Actions workflow dispatch", "parameters": {"type": "object", "properties": {"owner": {"type": "string", "description": "Repository owner"}, "repo": {"type": "string", "description": "Repository name"}, "workflow_id": {"type": "string", "description": "Workflow ID or filename"}, "ref": {"type": "string", "description": "Branch reference"}}, "required": ["owner", "repo", "workflow_id", "ref"]}},
    {"name": "search_code", "description": "Search code across GitHub repositories", "parameters": {"type": "object", "properties": {"query": {"type": "string", "description": "Code search query"}, "language": {"type": "string", "description": "Filter by language"}}, "required": ["query"]}},
    {"name": "list_branches", "description": "List branches in a GitHub repository", "parameters": {"type": "object", "properties": {"owner": {"type": "string", "description": "Repository owner"}, "repo": {"type": "string", "description": "Repository name"}, "protected": {"type": "boolean", "description": "Only protected branches"}}, "required": ["owner", "repo"]}},
    {"name": "create_repo", "description": "Create a new GitHub repository", "parameters": {"type": "object", "properties": {"name": {"type": "string", "description": "Repository name"}, "description": {"type": "string", "description": "Repository description"}, "private": {"type": "boolean", "description": "Private repo flag"}}, "required": ["name"]}},
    {"name": "get_commit", "description": "Get a GitHub commit by SHA", "parameters": {"type": "object", "properties": {"owner": {"type": "string", "description": "Repository owner"}, "repo": {"type": "string", "description": "Repository name"}, "sha": {"type": "string", "description": "Commit SHA"}}, "required": ["owner", "repo", "sha"]}},

    # Extra SaaS platforms to reach 200+ (70 additional tools across various platforms)
    # Stripe (8)
    {"name": "create_payment_intent", "description": "Create a payment intent in Stripe", "parameters": {"type": "object", "properties": {"amount": {"type": "integer", "description": "Amount in cents"}, "currency": {"type": "string", "description": "Three-letter currency code"}, "customer_id": {"type": "string", "description": "Stripe customer ID"}}, "required": ["amount", "currency"]}},
    {"name": "list_charges", "description": "List charges from Stripe account", "parameters": {"type": "object", "properties": {"limit": {"type": "integer", "description": "Max charges"}, "customer_id": {"type": "string", "description": "Filter by customer"}}, "required": []}},
    {"name": "create_customer", "description": "Create a customer in Stripe", "parameters": {"type": "object", "properties": {"email": {"type": "string", "description": "Customer email"}, "name": {"type": "string", "description": "Customer name"}, "metadata": {"type": "object", "description": "Custom metadata"}}, "required": ["email"]}},
    {"name": "retrieve_refund", "description": "Retrieve a refund by ID in Stripe", "parameters": {"type": "object", "properties": {"refund_id": {"type": "string", "description": "Refund ID"}}, "required": ["refund_id"]}},
    {"name": "create_subscription", "description": "Create a subscription in Stripe", "parameters": {"type": "object", "properties": {"customer_id": {"type": "string", "description": "Customer ID"}, "items": {"type": "array", "description": "Subscription items"}, "trial_period_days": {"type": "integer", "description": "Trial duration"}}, "required": ["customer_id", "items"]}},
    {"name": "list_products", "description": "List products in Stripe catalog", "parameters": {"type": "object", "properties": {"limit": {"type": "integer", "description": "Max products"}, "active": {"type": "boolean", "description": "Only active products"}}, "required": []}},
    {"name": "create_invoice_item", "description": "Add an invoice item in Stripe", "parameters": {"type": "object", "properties": {"customer_id": {"type": "string", "description": "Customer ID"}, "amount": {"type": "integer", "description": "Amount in cents"}, "currency": {"type": "string", "description": "Currency code"}, "description": {"type": "string", "description": "Item description"}}, "required": ["customer_id", "amount", "currency"]}},
    {"name": "cancel_subscription", "description": "Cancel a Stripe subscription", "parameters": {"type": "object", "properties": {"subscription_id": {"type": "string", "description": "Subscription ID"}, "invoice_now": {"type": "boolean", "description": "Generate final invoice"}}, "required": ["subscription_id"]}},

    # Datadog (6)
    {"name": "list_monitors", "description": "List monitors in Datadog account", "parameters": {"type": "object", "properties": {"tags": {"type": "string", "description": "Filter by tags"}, "page": {"type": "integer", "description": "Page number"}}, "required": []}},
    {"name": "query_metrics", "description": "Query time series metrics from Datadog", "parameters": {"type": "object", "properties": {"query": {"type": "string", "description": "Metrics query string"}, "from": {"type": "integer", "description": "Start timestamp"}, "to": {"type": "integer", "description": "End timestamp"}}, "required": ["query", "from", "to"]}},
    {"name": "create_dashboard", "description": "Create a dashboard in Datadog", "parameters": {"type": "object", "properties": {"title": {"type": "string", "description": "Dashboard title"}, "widgets": {"type": "array", "description": "Widget definitions"}, "layout_type": {"type": "string", "description": "Free or ordered"}}, "required": ["title", "widgets"]}},
    {"name": "get_monitor", "description": "Get a Datadog monitor by ID", "parameters": {"type": "object", "properties": {"monitor_id": {"type": "integer", "description": "Monitor ID"}}, "required": ["monitor_id"]}},
    {"name": "search_logs", "description": "Search logs in Datadog", "parameters": {"type": "object", "properties": {"query": {"type": "string", "description": "Log search query"}, "time_range": {"type": "object", "description": "Time range"}}, "required": ["query"]}},
    {"name": "mute_monitor", "description": "Mute a Datadog monitor", "parameters": {"type": "object", "properties": {"monitor_id": {"type": "integer", "description": "Monitor ID"}, "scope": {"type": "string", "description": "Mute scope"}}, "required": ["monitor_id"]}},

    # PagerDuty (6)
    {"name": "list_incidents", "description": "List incidents in PagerDuty", "parameters": {"type": "object", "properties": {"statuses": {"type": "array", "description": "Incident statuses"}, "limit": {"type": "integer", "description": "Max results"}}, "required": []}},
    {"name": "get_incident", "description": "Get incident details in PagerDuty", "parameters": {"type": "object", "properties": {"incident_id": {"type": "string", "description": "Incident ID"}}, "required": ["incident_id"]}},
    {"name": "acknowledge_incident", "description": "Acknowledge a PagerDuty incident", "parameters": {"type": "object", "properties": {"incident_id": {"type": "string", "description": "Incident ID"}, "from": {"type": "string", "description": "User email"}}, "required": ["incident_id", "from"]}},
    {"name": "resolve_incident", "description": "Resolve a PagerDuty incident", "parameters": {"type": "object", "properties": {"incident_id": {"type": "string", "description": "Incident ID"}}, "required": ["incident_id"]}},
    {"name": "list_services", "description": "List services in PagerDuty", "parameters": {"type": "object", "properties": {"limit": {"type": "integer", "description": "Max services"}, "query": {"type": "string", "description": "Search query"}}, "required": []}},
    {"name": "list_oncalls", "description": "List on-call schedules in PagerDuty", "parameters": {"type": "object", "properties": {"schedule_id": {"type": "string", "description": "Schedule ID filter"}}, "required": []}},

    # AWS (8)
    {"name": "list_ec2_instances", "description": "List EC2 instances in AWS region", "parameters": {"type": "object", "properties": {"region": {"type": "string", "description": "AWS region"}, "filters": {"type": "array", "description": "Instance filters"}}, "required": []}},
    {"name": "describe_s3_buckets", "description": "Describe all S3 buckets in AWS account", "parameters": {"type": "object", "properties": {"region": {"type": "string", "description": "AWS region"}}, "required": []}},
    {"name": "list_lambda_functions", "description": "List Lambda functions in AWS region", "parameters": {"type": "object", "properties": {"region": {"type": "string", "description": "AWS region"}, "max_items": {"type": "integer", "description": "Max results"}}, "required": []}},
    {"name": "send_sqs_message", "description": "Send a message to SQS queue", "parameters": {"type": "object", "properties": {"queue_url": {"type": "string", "description": "SQS queue URL"}, "message_body": {"type": "string", "description": "Message content"}}, "required": ["queue_url", "message_body"]}},
    {"name": "put_s3_object", "description": "Upload an object to S3 bucket", "parameters": {"type": "object", "properties": {"bucket": {"type": "string", "description": "Bucket name"}, "key": {"type": "string", "description": "Object key"}, "body": {"type": "string", "description": "Object content as base64"}}, "required": ["bucket", "key", "body"]}},
    {"name": "get_secret_value", "description": "Get a secret from AWS Secrets Manager", "parameters": {"type": "object", "properties": {"secret_id": {"type": "string", "description": "Secret name or ARN"}}, "required": ["secret_id"]}},
    {"name": "list_rds_instances", "description": "List RDS instances in AWS region", "parameters": {"type": "object", "properties": {"region": {"type": "string", "description": "AWS region"}}, "required": []}},
    {"name": "start_ec2_instance", "description": "Start a stopped EC2 instance", "parameters": {"type": "object", "properties": {"instance_id": {"type": "string", "description": "EC2 instance ID"}, "region": {"type": "string", "description": "AWS region"}}, "required": ["instance_id"]}},

    # Zendesk (6)
    {"name": "search_tickets", "description": "Search tickets in Zendesk", "parameters": {"type": "object", "properties": {"query": {"type": "string", "description": "Search query"}, "limit": {"type": "integer", "description": "Max results"}}, "required": ["query"]}},
    {"name": "create_ticket", "description": "Create a support ticket in Zendesk", "parameters": {"type": "object", "properties": {"subject": {"type": "string", "description": "Ticket subject"}, "description": {"type": "string", "description": "Ticket description"}, "priority": {"type": "string", "description": "Priority level"}}, "required": ["subject", "description"]}},
    {"name": "update_ticket", "description": "Update a Zendesk ticket", "parameters": {"type": "object", "properties": {"ticket_id": {"type": "integer", "description": "Ticket ID"}, "fields": {"type": "object", "description": "Fields to update"}}, "required": ["ticket_id", "fields"]}},
    {"name": "list_ticket_comments", "description": "List comments on a Zendesk ticket", "parameters": {"type": "object", "properties": {"ticket_id": {"type": "integer", "description": "Ticket ID"}}, "required": ["ticket_id"]}},
    {"name": "get_user", "description": "Get Zendesk user by ID", "parameters": {"type": "object", "properties": {"user_id": {"type": "integer", "description": "User ID"}}, "required": ["user_id"]}},
    {"name": "list_organizations", "description": "List organizations in Zendesk", "parameters": {"type": "object", "properties": {"page": {"type": "integer", "description": "Page number"}}, "required": []}},

    # Snowflake (6)
    {"name": "execute_snowflake_query", "description": "Execute SQL query on Snowflake", "parameters": {"type": "object", "properties": {"query": {"type": "string", "description": "SQL query"}, "warehouse": {"type": "string", "description": "Warehouse to use"}}, "required": ["query"]}},
    {"name": "list_databases", "description": "List databases in Snowflake account", "parameters": {"type": "object", "properties": {"like": {"type": "string", "description": "Name pattern filter"}}, "required": []}},
    {"name": "create_warehouse", "description": "Create a virtual warehouse in Snowflake", "parameters": {"type": "object", "properties": {"name": {"type": "string", "description": "Warehouse name"}, "size": {"type": "string", "description": "Warehouse size"}, "auto_suspend": {"type": "integer", "description": "Auto-suspend seconds"}}, "required": ["name", "size"]}},
    {"name": "describe_table", "description": "Describe table columns in Snowflake", "parameters": {"type": "object", "properties": {"database": {"type": "string", "description": "Database name"}, "schema": {"type": "string", "description": "Schema name"}, "table": {"type": "string", "description": "Table name"}}, "required": ["database", "schema", "table"]}},
    {"name": "list_tables", "description": "List tables in Snowflake schema", "parameters": {"type": "object", "properties": {"database": {"type": "string", "description": "Database name"}, "schema": {"type": "string", "description": "Schema name"}}, "required": ["database", "schema"]}},
    {"name": "get_query_history", "description": "Get query history for Snowflake account", "parameters": {"type": "object", "properties": {"time_range": {"type": "string", "description": "Time range filter"}}, "required": []}},

    # Mailchimp (5)
    {"name": "list_audiences", "description": "List Mailchimp audiences", "parameters": {"type": "object", "properties": {"page_size": {"type": "integer", "description": "Results per page"}}, "required": []}},
    {"name": "add_list_member", "description": "Add a member to Mailchimp audience list", "parameters": {"type": "object", "properties": {"list_id": {"type": "string", "description": "Audience list ID"}, "email": {"type": "string", "description": "Subscriber email"}, "status": {"type": "string", "description": "Subscription status"}}, "required": ["list_id", "email"]}},
    {"name": "create_campaign", "description": "Create an email campaign in Mailchimp", "parameters": {"type": "object", "properties": {"list_id": {"type": "string", "description": "Audience list ID"}, "subject": {"type": "string", "description": "Campaign subject"}, "from_name": {"type": "string", "description": "Sender name"}}, "required": ["list_id", "subject"]}},
    {"name": "send_campaign", "description": "Send a Mailchimp campaign immediately", "parameters": {"type": "object", "properties": {"campaign_id": {"type": "string", "description": "Campaign ID"}}, "required": ["campaign_id"]}},
    {"name": "get_campaign_report", "description": "Get report for a Mailchimp campaign", "parameters": {"type": "object", "properties": {"campaign_id": {"type": "string", "description": "Campaign ID"}}, "required": ["campaign_id"]}},

    # Shopify (5)
    {"name": "list_products", "description": "List products in Shopify store", "parameters": {"type": "object", "properties": {"limit": {"type": "integer", "description": "Max products"}, "status": {"type": "string", "description": "Product status"}}, "required": []}},
    {"name": "get_product", "description": "Get a Shopify product by ID", "parameters": {"type": "object", "properties": {"product_id": {"type": "integer", "description": "Product ID"}}, "required": ["product_id"]}},
    {"name": "create_order", "description": "Create a new order in Shopify", "parameters": {"type": "object", "properties": {"line_items": {"type": "array", "description": "Order line items"}, "customer_email": {"type": "string", "description": "Customer email"}}, "required": ["line_items"]}},
    {"name": "list_orders", "description": "List orders in Shopify store", "parameters": {"type": "object", "properties": {"status": {"type": "string", "description": "Order status filter"}, "limit": {"type": "integer", "description": "Max results"}}, "required": []}},
    {"name": "update_inventory", "description": "Update inventory quantity in Shopify", "parameters": {"type": "object", "properties": {"inventory_item_id": {"type": "integer", "description": "Inventory item ID"}, "location_id": {"type": "integer", "description": "Location ID"}, "quantity": {"type": "integer", "description": "New quantity"}}, "required": ["inventory_item_id", "location_id", "quantity"]}},

    # Sentry (4)
    {"name": "list_issues", "description": "List issues in Sentry project", "parameters": {"type": "object", "properties": {"project_id": {"type": "string", "description": "Sentry project ID"}, "stats_period": {"type": "string", "description": "Time period"}}, "required": ["project_id"]}},
    {"name": "get_issue_events", "description": "Get events for a Sentry issue", "parameters": {"type": "object", "properties": {"issue_id": {"type": "string", "description": "Issue ID"}}, "required": ["issue_id"]}},
    {"name": "create_alert_rule", "description": "Create an alert rule in Sentry", "parameters": {"type": "object", "properties": {"project_id": {"type": "string", "description": "Project ID"}, "name": {"type": "string", "description": "Alert name"}, "conditions": {"type": "object", "description": "Trigger conditions"}}, "required": ["project_id", "name", "conditions"]}},
    {"name": "resolve_issue", "description": "Resolve a Sentry issue", "parameters": {"type": "object", "properties": {"issue_id": {"type": "string", "description": "Issue ID"}}, "required": ["issue_id"]}},

    # Linear (5)
    {"name": "create_linear_issue", "description": "Create an issue in Linear", "parameters": {"type": "object", "properties": {"team_id": {"type": "string", "description": "Team ID"}, "title": {"type": "string", "description": "Issue title"}, "description": {"type": "string", "description": "Issue description"}}, "required": ["team_id", "title"]}},
    {"name": "search_linear_issues", "description": "Search issues in Linear workspace", "parameters": {"type": "object", "properties": {"query": {"type": "string", "description": "Search text"}, "limit": {"type": "integer", "description": "Max results"}}, "required": ["query"]}},
    {"name": "get_linear_issue", "description": "Get a Linear issue by ID", "parameters": {"type": "object", "properties": {"issue_id": {"type": "string", "description": "Issue ID"}}, "required": ["issue_id"]}},
    {"name": "list_linear_teams", "description": "List teams in Linear workspace", "parameters": {"type": "object", "properties": {"include_archived": {"type": "boolean", "description": "Include archived teams"}}, "required": []}},
    {"name": "update_linear_issue", "description": "Update a Linear issue state", "parameters": {"type": "object", "properties": {"issue_id": {"type": "string", "description": "Issue ID"}, "state_id": {"type": "string", "description": "New workflow state ID"}}, "required": ["issue_id", "state_id"]}},

    # Figma (4)
    {"name": "get_file_nodes", "description": "Get nodes from a Figma file", "parameters": {"type": "object", "properties": {"file_key": {"type": "string", "description": "Figma file key"}, "node_ids": {"type": "array", "description": "Node IDs to retrieve"}}, "required": ["file_key", "node_ids"]}},
    {"name": "get_file_styles", "description": "Get styles defined in a Figma file", "parameters": {"type": "object", "properties": {"file_key": {"type": "string", "description": "Figma file key"}}, "required": ["file_key"]}},
    {"name": "get_file_components", "description": "Get components from a Figma file", "parameters": {"type": "object", "properties": {"file_key": {"type": "string", "description": "Figma file key"}}, "required": ["file_key"]}},
    {"name": "search_figma_files", "description": "Search Figma files by name", "parameters": {"type": "object", "properties": {"query": {"type": "string", "description": "Search query"}, "project_id": {"type": "string", "description": "Project filter"}}, "required": ["query"]}},

    # GitLab (4)
    {"name": "list_merge_requests", "description": "List merge requests in GitLab project", "parameters": {"type": "object", "properties": {"project_id": {"type": "string", "description": "Project ID"}, "state": {"type": "string", "description": "MR state"}}, "required": ["project_id"]}},
    {"name": "create_gitlab_issue", "description": "Create an issue in GitLab project", "parameters": {"type": "object", "properties": {"project_id": {"type": "string", "description": "Project ID"}, "title": {"type": "string", "description": "Issue title"}, "labels": {"type": "array", "description": "Label names"}}, "required": ["project_id", "title"]}},
    {"name": "run_pipeline", "description": "Run a CI pipeline in GitLab", "parameters": {"type": "object", "properties": {"project_id": {"type": "string", "description": "Project ID"}, "ref": {"type": "string", "description": "Branch or tag"}}, "required": ["project_id", "ref"]}},
    {"name": "get_project", "description": "Get GitLab project details", "parameters": {"type": "object", "properties": {"project_id": {"type": "string", "description": "Project ID"}}, "required": ["project_id"]}},

    # Monday.com (4)
    {"name": "create_item", "description": "Create an item in Monday.com board", "parameters": {"type": "object", "properties": {"board_id": {"type": "integer", "description": "Board ID"}, "item_name": {"type": "string", "description": "Item name"}, "column_values": {"type": "object", "description": "Column values"}}, "required": ["board_id", "item_name"]}},
    {"name": "search_items", "description": "Search items in Monday.com by text", "parameters": {"type": "object", "properties": {"query": {"type": "string", "description": "Search query"}, "board_id": {"type": "integer", "description": "Board filter"}}, "required": ["query"]}},
    {"name": "get_board_items", "description": "Get all items from a Monday.com board", "parameters": {"type": "object", "properties": {"board_id": {"type": "integer", "description": "Board ID"}, "limit": {"type": "integer", "description": "Max items"}}, "required": ["board_id"]}},
    {"name": "update_item_value", "description": "Update a column value on Monday.com item", "parameters": {"type": "object", "properties": {"item_id": {"type": "integer", "description": "Item ID"}, "column_id": {"type": "string", "description": "Column ID"}, "value": {"type": "object", "description": "New column value"}}, "required": ["item_id", "column_id", "value"]}},

    # Supabase (4)
    {"name": "query_supabase_table", "description": "Query a Supabase table with filters", "parameters": {"type": "object", "properties": {"table": {"type": "string", "description": "Table name"}, "select": {"type": "string", "description": "Columns to select"}, "filter": {"type": "object", "description": "Filter conditions"}}, "required": ["table"]}},
    {"name": "insert_supabase_row", "description": "Insert a row into Supabase table", "parameters": {"type": "object", "properties": {"table": {"type": "string", "description": "Table name"}, "values": {"type": "object", "description": "Column values"}}, "required": ["table", "values"]}},
    {"name": "update_supabase_row", "description": "Update rows in Supabase table", "parameters": {"type": "object", "properties": {"table": {"type": "string", "description": "Table name"}, "match": {"type": "object", "description": "Match conditions"}, "values": {"type": "object", "description": "Updated values"}}, "required": ["table", "match", "values"]}},
    {"name": "delete_supabase_row", "description": "Delete rows from Supabase table", "parameters": {"type": "object", "properties": {"table": {"type": "string", "description": "Table name"}, "match": {"type": "object", "description": "Match conditions"}}, "required": ["table", "match"]}},

    # Vercel (4)
    {"name": "list_deployments", "description": "List deployments in Vercel project", "parameters": {"type": "object", "properties": {"project_id": {"type": "string", "description": "Project ID"}, "limit": {"type": "integer", "description": "Max deployments"}}, "required": []}},
    {"name": "get_deployment", "description": "Get Vercel deployment by ID", "parameters": {"type": "object", "properties": {"deployment_id": {"type": "string", "description": "Deployment ID"}}, "required": ["deployment_id"]}},
    {"name": "create_deployment", "description": "Deploy a project to Vercel", "parameters": {"type": "object", "properties": {"project_id": {"type": "string", "description": "Project ID"}, "branch": {"type": "string", "description": "Git branch"}}, "required": ["project_id"]}},
    {"name": "list_projects", "description": "List projects in Vercel account", "parameters": {"type": "object", "properties": {"limit": {"type": "integer", "description": "Max projects"}}, "required": []}},

    # Cloudflare (3)
    {"name": "purge_cache", "description": "Purge Cloudflare cache for a zone", "parameters": {"type": "object", "properties": {"zone_id": {"type": "string", "description": "Cloudflare zone ID"}, "files": {"type": "array", "description": "URLs to purge"}}, "required": ["zone_id"]}},
    {"name": "list_dns_records", "description": "List DNS records for a Cloudflare zone", "parameters": {"type": "object", "properties": {"zone_id": {"type": "string", "description": "Zone ID"}, "type": {"type": "string", "description": "DNS record type filter"}}, "required": ["zone_id"]}},
    {"name": "create_dns_record", "description": "Create a DNS record in Cloudflare", "parameters": {"type": "object", "properties": {"zone_id": {"type": "string", "description": "Zone ID"}, "type": {"type": "string", "description": "Record type"}, "name": {"type": "string", "description": "Record name"}, "content": {"type": "string", "description": "Record value"}}, "required": ["zone_id", "type", "name", "content"]}},

    # Netlify (3)
    {"name": "list_sites", "description": "List sites in Netlify account", "parameters": {"type": "object", "properties": {"page": {"type": "integer", "description": "Page number"}}, "required": []}},
    {"name": "get_deploy", "description": "Get a Netlify deploy by ID", "parameters": {"type": "object", "properties": {"site_id": {"type": "string", "description": "Site ID"}, "deploy_id": {"type": "string", "description": "Deploy ID"}}, "required": ["site_id", "deploy_id"]}},
    {"name": "create_site", "description": "Create a new site in Netlify", "parameters": {"type": "object", "properties": {"name": {"type": "string", "description": "Site name"}, "repo_url": {"type": "string", "description": "Git repository URL"}}, "required": ["name"]}},

    # Intercom (3)
    {"name": "search_conversations", "description": "Search conversations in Intercom", "parameters": {"type": "object", "properties": {"query": {"type": "object", "description": "Search query"}, "per_page": {"type": "integer", "description": "Results per page"}}, "required": ["query"]}},
    {"name": "create_contact", "description": "Create a contact in Intercom", "parameters": {"type": "object", "properties": {"email": {"type": "string", "description": "Contact email"}, "name": {"type": "string", "description": "Contact name"}}, "required": ["email"]}},
    {"name": "send_message", "description": "Send a message via Intercom", "parameters": {"type": "object", "properties": {"contact_id": {"type": "string", "description": "Contact ID"}, "body": {"type": "string", "description": "Message content"}, "message_type": {"type": "string", "description": "In-app or email"}}, "required": ["contact_id", "body"]}},

    # OpenAI (3)
    {"name": "list_assistants", "description": "List OpenAI assistants", "parameters": {"type": "object", "properties": {"limit": {"type": "integer", "description": "Max assistants"}, "order": {"type": "string", "description": "Sort order"}}, "required": []}},
    {"name": "create_thread", "description": "Create a conversation thread in OpenAI", "parameters": {"type": "object", "properties": {"messages": {"type": "array", "description": "Initial messages"}}, "required": []}},
    {"name": "run_assistant", "description": "Run an OpenAI assistant on a thread", "parameters": {"type": "object", "properties": {"assistant_id": {"type": "string", "description": "Assistant ID"}, "thread_id": {"type": "string", "description": "Thread ID"}}, "required": ["assistant_id", "thread_id"]}},

    # Dropbox (3)
    {"name": "list_folder", "description": "List files in Dropbox folder", "parameters": {"type": "object", "properties": {"path": {"type": "string", "description": "Folder path"}, "recursive": {"type": "boolean", "description": "Include subfolders"}}, "required": ["path"]}},
    {"name": "upload_file", "description": "Upload a file to Dropbox", "parameters": {"type": "object", "properties": {"path": {"type": "string", "description": "Destination path"}, "contents": {"type": "string", "description": "File content as base64"}}, "required": ["path", "contents"]}},
    {"name": "search_files", "description": "Search files in Dropbox", "parameters": {"type": "object", "properties": {"query": {"type": "string", "description": "Search query"}, "max_results": {"type": "integer", "description": "Max results"}}, "required": ["query"]}},
]
