pub mod registry;
pub mod bash;
pub mod edit;
pub mod path;
pub mod read_tool;
pub mod write_tool;
pub mod glob_tool;
pub mod grep_tool;
pub mod web_tool;
pub mod memory_tool;
pub mod delegate;
pub mod todo_tool;
pub mod mcp_client;
pub use registry::{ToolFn, ToolRegistry};