pub mod archive_tool;
pub mod bash;
#[cfg(feature = "tools-browser")]
pub mod browser_tool;
pub mod chart_tool;
pub mod cli_tools;
pub mod csv_tool;
pub mod delegate;
#[cfg(feature = "tools-desktop")]
pub mod desktop_tool;
pub mod edit;
pub mod final_answer;
pub mod git_tool;
pub mod glob_tool;
pub mod grep_tool;
pub mod groups;
pub mod json_tool;
pub mod litertlm;
pub mod llamacpp;
pub mod mcp_client;
pub mod nvidia_cloud_functions;
pub mod ollama_web_tools;
pub mod memory_tool;
pub mod mtp;
pub mod path;
#[cfg(feature = "tools-pdf")]
pub mod pdf_tool;
pub mod read_tool;
pub mod registration;
pub mod registry;
pub mod scrape_tool;
#[cfg(feature = "tools-screenshot")]
pub mod screenshot;
pub mod searchhq;
pub mod sequential_thinking;
pub mod time_tool;
pub mod todo_tool;
pub mod web_tool;
pub mod write_tool;
pub mod you_tools;
pub use registration::{register_all_tools, setup_tools};
pub use registry::{ToolFn, ToolRegistry};
