pub mod registry;
pub mod bash;
pub mod edit;
pub mod path;
pub mod read_tool;
pub mod write_tool;
pub mod glob_tool;
pub mod grep_tool;
pub mod web_tool;
pub mod memory_tool;
pub mod delegate;
pub mod todo_tool;
pub mod scrape_tool;
pub mod csv_tool;
pub mod archive_tool;
pub mod json_tool;
pub mod mcp_client;
#[cfg(feature = "tools-screenshot")]
pub mod screenshot;
pub mod chart_tool;
#[cfg(feature = "tools-pdf")]
pub mod pdf_tool;
#[cfg(feature = "tools-desktop")]
pub mod desktop_tool;
#[cfg(feature = "tools-browser")]
pub mod browser_tool;
pub use registry::{ToolFn, ToolRegistry};